/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistasPuntosR;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;

/**
 *
 * @author Byron
 */
public class MostrarPuntos extends javax.swing.JPanel {

    /**
     * Creates new form MostrarPuntos
     */
    public MostrarPuntos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        setBackground(new java.awt.Color(102, 190, 230));
        setMaximumSize(new java.awt.Dimension(500, 377));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Direccion", "Tipo de reciclaje", "Ciudad", "Capacidad", "ID", "Vaciado en dias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });


        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        nuevaTabla();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaTabla() {
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn( "Direccion");
        tabla.addColumn( "Tipo de reciclaje");
        tabla.addColumn("Ciudad");
        tabla.addColumn("Capacidad");
        tabla.addColumn("ID");
        tabla.addColumn( "Vaciado en dias");
        jTable1.setModel(tabla);

        BufferedReader lector;
        String linea;
        try {
            lector = new BufferedReader(new FileReader("src/main/resources/puntos/CSVpuntos.csv"));
            while ((linea = lector.readLine()) != null) {
                String str = linea;
                String[] columns = str.split("[;]", 0);
                tabla.addRow(columns);
                System.out.println("SE AÑADIERON LOS DATOS");
            }
            jTable1.setModel(tabla);
            lector.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
